# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mohammad Armoun
title: Backend/Data engineer
email: mohamad.armoun@gmail.com
website: embeddedandmore.github.io/MyCv/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  EmbeddedAndMore
stackoverflow_username: "4527628"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: mohammad-armoun-91470190
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey there, folks! I go by the name Mohammad, but you can just call me Mo - your friendly neighborhood Backend/Data magician. Yep, I'm the tech wizard who dances with hardware and occasionally dabbles in some embedded development wizardry on the side.

  You know, I've been in the software game for over a decade, hopping around different corners of the development universe. From crafting code for teeny-tiny embedded systems to conjuring up cloud-native marvels, I've seen it all.

  But wait, there's more! My true claim to fame? I'm like the Usain Bolt of code when it comes to whipping up lightning-fast, real-time data analysis. Think milliseconds, my friends. So, whether it's software or a marathon, I'm here to make every millisecond count! :rocket:

content:
#   - title: Projects # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: avodaq AG
        link: avodaq.com
        # link_text: boringcompany.com
        sub_title: Software developerok
        caption: November 2022 - Present
        quote: >
          An IT/Security/Software infrastructure provider company in Germany.
        description: | # this will include new lines to allow paragraphs
          **Backend Development:** Full-Stack Django based CISCO Identity Services Engine (ISE) manager.<br/>
          **Backend/Development:** Online healthcare appointment (telemedication) platform.<br/>
          **IoT Data engineering:** Large scale store equipment monitoring/maintenance.
          #### Tech-Stack
          - Django, Celery, MySql, Redis, Numpy, Pandas, Dask, JS, Async, Multiprocess
          - FastApi, MySql, Redis
          - Embedded C, Django, Numpy, Dask, InfluxDB, Apcahe Kafka, Storm

          #### Software Architechture
          - Clean code, event-driven
          - DDD
          - Microservice, Clean code

          #### Design paterns
          - Repository, Singleton, Unit of Work, Decorator
          - Repository, Singleton, Unit of Work, Decorator,Adapter, 
          - Repository, Decorator, Adapter

          #### Deployement
          - Docker, docker-compose
          - Docker, Kubernites
          - Docker, Kubernites
      - layout: left
        title: fabforce GmbH & Co. KG
        link: www.fabforce.com
        sub_title: Data Enginner
        caption: Mar 2021 - Oct 2022
        quote: >
          Intelligent data analysis specialied for factories, plants and production line to improve productivity and yield, lower maintenance costs and reduce defects in production.
        description: | # this will include new lines to allow paragraphs
            **Data engineering:** Data aggregation, real-time preprocessing and analysis (ELT, ETL).
            #### Tech-Stack
            - Dask, Celery, Numpy, Scipy, Scikit-learn, Flask, Python, C++, PyBind11,, Streamz
            - Interfaces: S7, MQTT, OPC-UA, Serial

            #### Software Architechture
            - Clean code, Microservice

            #### Design paterns
            - Repository, Singleton, Decorator, Adapter

            #### Deployement
            - Docker, docker-compose
      - layout: left
        title: eido Data
        # link: www.fabforce.com
        sub_title: Software Developer
        caption: Jul 2019 - Jan 2021
        quote: >
          Providing ML tool for visualization, Preprocessing and Model management tool specialized for metalorgy applications.
        description: | # this will include new lines to allow paragraphs
            **Software developer:** Data aggregation, real-time preprocessing and analysis (ELT, ETL)
            #### Tech-Stack
            -  Celery, Flask, Numpy, Pandas, Scikit-learn, WPF

            #### Software Architechture
            - Clean code, DDD
            
            #### Design paterns
            - Singleton, Decorator, Adapter

            #### Deployement
            - Docker, docker-compose, exe installer

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
